textileio/js-textile

src/ThreadsConfig.ts
src/index.ts

Signed-off-by: andrew <andrew@textile.io>

sessions: allow app to restart from previous session

---

package-lock.json
package.json
src/API.spec.ts

Update @textile/threads-core package

---

src/users.spec.ts

@andrewxhill , I've updated this test to ensure that the user context is _fully isolated_ from the developer context... that way, we can be sure this is a realistic usage scenario.

Fully isolate user context

---

packages/buckets/src/buckets.ts
packages/buckets/src/index.ts

fix(apis): adds bucket helpers withUserAuth and withUserKey

---

packages/buckets/package-lock.json
packages/buckets/package.json
packages/buckets/src/buckets.ts

fixes https://github.com/textileio/js-hub/issues/270

feat(init): adds method to init from client directly

---

packages/buckets/package-lock.json
packages/buckets/package.json
packages/buckets/src/buckets.spec.ts
packages/buckets/src/buckets.ts

wanted to get the archive commands available even if not in production yet. noticed a few other apis that were behind so added those as well.

feat(api): adds missing bucket apis to js

---

config/api-extractor.json
etc/hub.api.md
packages/buckets/package-lock.json
packages/hub/package-lock.json
packages/hub/package.json
packages/hub/src/index.ts
website/sidebars.json

fixes https://github.com/textileio/js-hub/issues/378

chore(api): remove database from hub exported classes and docs

---

packages/buckets/package.json
packages/buckets/src/api/index.ts
packages/buckets/src/buckets.ts
packages/buckets/src/utils.ts
packages/grpc-authentication/README.md
packages/grpc-authentication/package.json
packages/grpc-authentication/src/index.ts
packages/grpc-authentication/tsconfig.json
packages/grpc-connection/README.md
packages/grpc-connection/package.json
packages/grpc-connection/src/index.ts
packages/grpc-connection/tsconfig.json
packages/users/package.json
packages/users/src/api/index.ts
packages/users/src/users.ts

trying to further atomize these units a bit so they are functionally useful in a plug&play way

shared unary connection and authentication

---

packages/crypto/package-lock.json
packages/crypto/package.json
packages/crypto/src/identity.ts
packages/crypto/src/keypair.spec.ts
packages/crypto/src/keypair.ts
packages/crypto/src/utils.ts
packages/grpc-authentication/package.json
packages/grpc-connection/package.json

Some doc strings for your PR @andrewxhill

Additional docs strings + details

---

package.json
packages/buckets/src/buckets.ts

fix(api): ensure threadid in return

---

etc/hub.api.md
packages/buckets/package-lock.json
packages/buckets/package.json
packages/hub-threads-client/package-lock.json
packages/hub-threads-client/package.json

Bump @textile/threads-client from 0.11.0 to 0.11.1
Fixes #480
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

chore(deps): bump @textile/threads-client from 0.11.0 to 0.11.1 fix #480

---

etc/hub.api.md
packages/buckets/package-lock.json
packages/buckets/package.json
packages/buckets/src/api/index.ts
packages/buckets/src/buckets.ts
packages/grpc-authentication/src/index.ts
packages/hub-threads-client/package-lock.json
packages/hub-threads-client/package.json
packages/hub/package-lock.json
packages/hub/package.json
packages/pow/package-lock.json
packages/pow/package.json
packages/pow/src/api/index.ts
packages/pow/src/pow.ts
packages/users/package-lock.json
packages/users/package.json
packages/users/src/users.ts
website/sidebars.json

fixes https://github.com/textileio/js-hub/issues/488 among others

feat(setPath): missed api method for release

---

package-lock.json
package.json
packages/buckets/package-lock.json
packages/buckets/package.json
packages/hub-threads-client/package-lock.json
packages/hub-threads-client/package.json

This updates the threads-client version (and the threads version, which appears to be in devDeps). It likely requires some docs updates, which should probably just be added to this PR. (cc @andrewxhill).
Tests should all be passing, no new tests on the hub side of things though.

Update client version for release

---

packages/buckets/src/api/index.ts

removed this in a previous release. spaced it on why it was needed, added a note in the docstring now

feat(ci): adds minimal api connector for ci action

---

package.json

Tiny PR that updates the test script, fixing a bug where calling test (rather than each individual script) throws.

Fix test npm script call

---

packages/buckets/package-lock.json
packages/buckets/package.json
packages/buckets/src/api/index.ts
packages/buckets/src/buckets.spec.ts
packages/buckets/src/buckets.ts
packages/grpc-connection/src/index.ts
packages/hub-threads-client/package-lock.json
packages/hub-threads-client/package.json
packages/hub/package.json
packages/pow/package-lock.json
packages/pow/package.json
packages/users/package-lock.json
packages/users/package.json

chore(api): updates protobufs; updates link request options

---

packages/pow/package-lock.json
packages/pow/package.json

Update to latest powergate grpc bindings

---

packages/buckets/src/api/index.ts

using midpoint recommendation here https://github.com/grpc/grpc.github.io/issues/371

fix(api): 256kb to 32kib chunking for buckets

---

lerna.json

This switching to using Lerna's built-in support for conventional commits handling. This will read our commit messages (so even if you squash, you should still use conventional commit messages) to auto-generate our changelogs, and these are automatically committed and pushed on releases. This will also take care of automatically determining sermver bumps if we let it/want it to. Including managing pre-releases and more. We can always override these settings, so we're not locked in, but it does alleviate a lot of the cognitive burden of trying to remember when to bump on major/minor etc.
Should not affect tests

Start using conventional commits auto-publishing

---

packages/buckets/src/index.ts
packages/crypto/package-lock.json
packages/crypto/package.json
packages/crypto/src/index.ts
packages/crypto/src/keypair.spec.ts
packages/crypto/src/keypair.ts
packages/crypto/src/utils.ts

Fixes #652 
Exists tests should continue to pass.

Export AbortController and AbortSignal for downstream consumers

---

packages/buckets/README.md
packages/crypto/README.md
packages/grpc-authentication/README.md
packages/grpc-authentication/src/index.ts
packages/grpc-connection/README.md
packages/hub-filecoin/README.md
packages/hub-threads-client/README.md
packages/users/README.md
packages/users/src/index.ts
packages/users/src/spec.util.ts
packages/users/src/users.spec.ts
packages/users/src/users.ts

Correct installation instructions, plus some linter fixes and better external api return type coverage in users library.
Should not affect tests.

Update readmes and linter fixes

---

packages/hub-filecoin/package-lock.json
rollup.config.js

Fixes a critical typo that was leading to significantly larger bundle sizes, and versioning issues on builds.
Should not affects tests, just publishing.

Correctly bundle hub-threads-client

---

etc/hub.api.md
packages/hub-filecoin/package-lock.json
packages/hub-filecoin/package.json
packages/hub-filecoin/src/api/index.ts
packages/hub-filecoin/src/filecoin.ts
packages/hub-filecoin/src/types.ts

There were a couple changes to model types and a new api function `cidSummary`.

Update to powergate 2.0 bindings

---

packages/admin/src/admin.spec.ts
packages/admin/src/admin.ts
packages/admin/src/index.ts

Just some nits discovered while working on the hub dashboard stuff.

Support scoped keys and better type exports

---

packages/admin/src/admin.spec.ts
packages/admin/src/admin.ts
packages/admin/src/api/index.ts

Some more nits around key generation from working on hub dash.

Expose type and secure on create

---

packages/buck-util/src/index.ts

fix(util): repeated ipfs prefix on ipfs link

---

packages/threaddb/README.md

Pull in content from original repo
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

Update threaddb readme

---

packages/client/src/index.ts

Wrap getTokenChallenge callback call in try/catch

---

packages/client/src/index.ts

Signed-off-by: Aaron Sutula <hi@asutula.com>

fix a link in doc comment

---

packages/threaddb/src/middleware/schemas/index.ts

Stateless schema validator
